// Bakes src/lib/upgrade-planner/honing-data.ts from the game tables in Maxroll's planner feed
// (https://assets-ng.maxroll.gg/laplanner/game/stats.json). Run once per game patch:
//   node scripts/bake-honing.mjs
// Only the handful of numbers the simulator needs are kept: main stat / Weapon Power by honing
// level, and cumulative advanced honing stats, for the T4 1675 "Destined Tremor" set.

import fs from 'node:fs';

const CACHE = 'cache/maxroll-stats.json';
if (!fs.existsSync(CACHE)) {
	fs.mkdirSync('cache', { recursive: true });
	const res = await fetch('https://assets-ng.maxroll.gg/laplanner/game/stats.json');
	if (!res.ok) throw new Error(`stats.json: ${res.status}`);
	fs.writeFileSync(CACHE, await res.text());
}
const { itemLevel, amplification } = JSON.parse(fs.readFileSync(CACHE, 'utf8'));

const BASE_ILVL = 1675;
const MAX_HONING = 25;
const MAX_ADVANCED = 40;
// levelOption ids (item table) and advanced-honing groups for each slot; the DEX variants are used,
// STR/INT carry identical numbers.
const SLOTS = {
	weapon: { levelOption: 12159000, amp: 1010, stat: 151 },
	head: { levelOption: 12159021, amp: 2110, stat: 4 },
	upper_body: { levelOption: 12159022, amp: 3110, stat: 4 },
	lower_body: { levelOption: 12159023, amp: 4110, stat: 4 },
	hand: { levelOption: 12159024, amp: 5110, stat: 4 },
	shoulder: { levelOption: 12159025, amp: 6110, stat: 4 }
};

const statOf = (stats, stat) => (stats ?? []).filter((s) => s.stat === stat).reduce((a, s) => a + s.value, 0);

const out = {};
for (const [slot, { levelOption, amp, stat }] of Object.entries(SLOTS)) {
	const honing = Array.from({ length: MAX_HONING + 1 }, (_, h) =>
		statOf(itemLevel[`${levelOption}#${BASE_ILVL + 5 * h}`], stat)
	);
	// Advanced honing runs in two stages (1–20, 21–40); each stage's table is cumulative within it.
	const stage = (l) => statOf(amplification[`${amp}#${l}`]?.stats, stat);
	const advanced = Array.from({ length: MAX_ADVANCED + 1 }, (_, l) => stage(Math.min(l, 20)) + (l > 20 ? stage(l) : 0));
	if (honing.some((v) => !v) || advanced[MAX_ADVANCED] === 0) throw new Error(`missing data for ${slot}`);
	out[slot] = { honing, advanced };
}

const body = `// Generated by scripts/bake-honing.mjs from the game's item tables (via Maxroll's planner feed).
// Do not edit by hand. T4 1675 "Destined Tremor" gear; armor values are main stat, weapon values are Weapon Power.
// honing[h] = stat at +h; advanced[l] = cumulative stat from advanced honing level l.

export const HONING_SLOTS = ${JSON.stringify(Object.keys(SLOTS))} as const;
export type HoningSlot = (typeof HONING_SLOTS)[number];

export const HONING_TABLE: Record<HoningSlot, { honing: number[]; advanced: number[] }> = ${JSON.stringify(out, null, '\t')};
`;
fs.writeFileSync('src/lib/upgrade-planner/honing-data.ts', body);
console.log('wrote honing-data.ts', Object.fromEntries(Object.entries(out).map(([k, v]) => [k, [v.honing[21], v.advanced[40]]])));
